baseURL = "http://innbiosights.netlify.io"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Bigspring Light"
[markup.goldmark.renderer]
unsafe = true
